from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.product import ProductCatalog

DEFAULT_PRODUCTS = [
    # ── OILY SKIN ──────────────────────────────────────────────────────────
    ProductCatalog(sku="DRR-ACN-001", name="Dr Rashel Salicylic Acid Clear Skin Serum",
        ingredients_csv="Salicylic Acid,Niacinamide,Tea Tree,Zinc,Glycerin,Aloe Vera", stock=24,
        price=1200.0, category="Serum",
        description="Oil control serum with salicylic acid and niacinamide to clear pores and reduce acne blemishes. Mattifying formula for oily skin.",
        image_url=None),
    ProductCatalog(sku="DRR-OIL-002", name="Dr Rashel Niacinamide Pore Minimizer Toner",
        ingredients_csv="Niacinamide,Zinc,Salicylic Acid,Witch Hazel,Glycerin", stock=20,
        price=950.0, category="Toner",
        description="Niacinamide toner for pore minimizing and oil control. Mattifying formula that balances sebum production.",
        image_url=None),
    ProductCatalog(sku="NEU-CLY-003", name="Neutrogena Deep Clean Clay Face Wash",
        ingredients_csv="Clay,Charcoal,Salicylic Acid,Glycerin", stock=30,
        price=800.0, category="Cleanser",
        description="Deep clean charcoal clay face wash that draws out impurities from pores. Ideal for oily and combination skin.",
        image_url=None),
    ProductCatalog(sku="GRN-OIL-004", name="Garnier Oil Control Moisturizer SPF 15",
        ingredients_csv="Niacinamide,Zinc,Glycerin,Vitamin E", stock=25,
        price=750.0, category="Moisturizer",
        description="Lightweight oil control moisturizer with SPF protection. Mattifying formula for oily to combination skin.",
        image_url=None),
    ProductCatalog(sku="INS-OIL-005", name="Innisfree No Sebum Mineral Powder",
        ingredients_csv="Niacinamide,Zinc,Clay,Silica", stock=18,
        price=1100.0, category="Powder",
        description="Oil control setting powder with niacinamide that keeps skin mattifying all day. Controls shine for oily skin.",
        image_url=None),
    ProductCatalog(sku="SKN-OIL-006", name="Skintific Mugwort Pore Tightening Serum",
        ingredients_csv="Niacinamide,Salicylic Acid,Zinc,Mugwort Extract,Clay", stock=22,
        price=1350.0, category="Serum",
        description="Pore tightening serum with salicylic acid and niacinamide for oily skin. Reduces excess sebum and mattifies skin.",
        image_url=None),
    ProductCatalog(sku="CEL-OIL-007", name="Cetaphil Oily Skin Cleanser",
        ingredients_csv="Niacinamide,Zinc PCA,Glycerin,Panthenol", stock=28,
        price=1800.0, category="Cleanser",
        description="Gentle yet effective cleanser for oily skin. Controls oil production without over-drying. Pore-refining formula.",
        image_url=None),
    ProductCatalog(sku="LAR-OIL-008", name="La Roche-Posay Effaclar Purifying Foaming Gel",
        ingredients_csv="Salicylic Acid,Zinc,Niacinamide,Glycerin", stock=16,
        price=3500.0, category="Cleanser",
        description="Purifying foaming gel cleanser for oily and acne-prone skin. Removes excess oil and unclogs pores.",
        image_url=None),
    ProductCatalog(sku="PON-OIL-009", name="Pond's Pure Bright Oil Control Face Wash",
        ingredients_csv="Salicylic Acid,Niacinamide,Clay,Glycerin", stock=35,
        price=550.0, category="Cleanser",
        description="Oil control face wash with salicylic acid. Removes excess oil and keeps skin fresh and mattifying.",
        image_url=None),
    ProductCatalog(sku="SKN-TON-010", name="Some By Mi AHA BHA PHA 30 Days Miracle Toner",
        ingredients_csv="Salicylic Acid,Glycolic Acid,Niacinamide,Tea Tree,Aloe Vera", stock=20,
        price=2200.0, category="Toner",
        description="Exfoliating toner with AHA BHA PHA for clear and blemish-free skin. Refines pores and controls oil.",
        image_url=None),

    # ── DRY SKIN ───────────────────────────────────────────────────────────
    ProductCatalog(sku="EST-HYD-010", name="Estelin Deep Hydration Hyaluronic Acid Cream",
        ingredients_csv="Hyaluronic Acid,Ceramides,Glycerin,Shea Butter,Squalane", stock=18,
        price=1500.0, category="Moisturizer",
        description="Deeply hydrating moisturizer with hyaluronic acid and ceramides for dry and dehydrated skin. Nourishing formula.",
        image_url=None),
    ProductCatalog(sku="CET-HYD-011", name="CeraVe Hydrating Facial Cleanser",
        ingredients_csv="Ceramides,Hyaluronic Acid,Glycerin,Niacinamide", stock=22,
        price=1800.0, category="Cleanser",
        description="Gentle hydrating cleanser with ceramides and hyaluronic acid. Nourishing formula for dry skin.",
        image_url=None),
    ProductCatalog(sku="EST-SHE-012", name="Estelin Shea Butter Intensive Body Lotion",
        ingredients_csv="Shea Butter,Glycerin,Vitamin E,Squalane,Ceramides", stock=15,
        price=1100.0, category="Body Lotion",
        description="Intensively nourishing body lotion with shea butter and vitamin E. Moisturizing formula for extremely dry skin.",
        image_url=None),
    ProductCatalog(sku="ORD-HYA-013", name="The Ordinary Hyaluronic Acid 2% + B5",
        ingredients_csv="Hyaluronic Acid,Vitamin B5,Glycerin,Ceramides", stock=19,
        price=2200.0, category="Serum",
        description="Hydrating serum with multi-weight hyaluronic acid and vitamin B5. Plumps and hydrates dehydrated skin.",
        image_url=None),
    ProductCatalog(sku="CET-MOI-014", name="CeraVe Moisturizing Cream",
        ingredients_csv="Ceramides,Hyaluronic Acid,Glycerin,Shea Butter,Niacinamide", stock=24,
        price=2500.0, category="Moisturizer",
        description="Rich moisturizing cream with ceramides that restores the skin barrier for dry and very dry skin.",
        image_url=None),
    ProductCatalog(sku="VAZ-DRY-015", name="Vaseline Intensive Care Dry Skin Lotion",
        ingredients_csv="Glycerin,Petroleum Jelly,Shea Butter,Vitamin E", stock=40,
        price=600.0, category="Body Lotion",
        description="Intensive moisturizing lotion for dry skin. Nourishing formula with glycerin and shea butter to heal dry skin.",
        image_url=None),
    ProductCatalog(sku="NTG-DRY-016", name="Neutrogena Hydro Boost Water Gel",
        ingredients_csv="Hyaluronic Acid,Glycerin,Ceramides,Squalane", stock=20,
        price=2800.0, category="Moisturizer",
        description="Lightweight water gel moisturizer with hyaluronic acid that deeply hydrates and plumps dry skin all day.",
        image_url=None),
    ProductCatalog(sku="AVN-DRY-017", name="Aveeno Daily Moisturizing Lotion",
        ingredients_csv="Oat,Glycerin,Shea Butter,Ceramides,Vitamin E", stock=22,
        price=1900.0, category="Body Lotion",
        description="Daily moisturizing lotion with oat for dry skin. Nourishing formula that hydrates and soothes all day.",
        image_url=None),
    ProductCatalog(sku="SKN-DRY-018", name="Skintific 5X Ceramide Barrier Serum",
        ingredients_csv="Ceramides,Hyaluronic Acid,Glycerin,Niacinamide,Squalane", stock=16,
        price=1800.0, category="Serum",
        description="Barrier-repairing serum with 5 types of ceramides for dry and damaged skin. Deeply moisturizing formula.",
        image_url=None),
    ProductCatalog(sku="BEU-DRY-019", name="Bioderma Atoderm Intensive Body Balm",
        ingredients_csv="Shea Butter,Ceramides,Glycerin,Vitamin E,Squalane", stock=14,
        price=3800.0, category="Body Balm",
        description="Intensive body balm for very dry skin. Rich nourishing formula with ceramides and shea butter for deep hydration.",
        image_url=None),
    ProductCatalog(sku="LAR-DRY-020", name="La Roche-Posay Lipikar Balm AP+",
        ingredients_csv="Shea Butter,Ceramides,Niacinamide,Glycerin,Aqua Posae Filiformis", stock=12,
        price=4200.0, category="Body Balm",
        description="Soothing body balm for dry and atopic skin. Restores the skin barrier and provides long-lasting moisture.",
        image_url=None),

    # ── SENSITIVE SKIN ─────────────────────────────────────────────────────
    ProductCatalog(sku="AVN-SEN-021", name="Aveeno Calm + Restore Oat Gel Moisturizer",
        ingredients_csv="Oat,Panthenol,Aloe Vera,Ceramides,Glycerin", stock=14,
        price=2500.0, category="Moisturizer",
        description="Gentle soothing gel moisturizer with oat and panthenol. Calming formula for sensitive skin that reduces redness.",
        image_url=None),
    ProductCatalog(sku="LAR-SEN-022", name="La Roche-Posay Toleriane Gentle Cleanser",
        ingredients_csv="Ceramides,Glycerin,Niacinamide,Panthenol", stock=16,
        price=3200.0, category="Cleanser",
        description="Ultra-gentle soothing cleanser for sensitive skin. Calming formula with ceramides that maintains the skin barrier.",
        image_url=None),
    ProductCatalog(sku="CEN-SEN-023", name="Centella Asiatica Calming Serum",
        ingredients_csv="Centella,Aloe Vera,Chamomile,Panthenol,Glycerin", stock=21,
        price=1600.0, category="Serum",
        description="Centella asiatica calming serum for sensitive and irritated skin. Soothing formula with aloe and chamomile to reduce redness.",
        image_url=None),
    ProductCatalog(sku="BIO-SEN-024", name="Bioderma Sensibio H2O Micellar Water",
        ingredients_csv="Cucumber Extract,Panthenol,Aloe Vera,Glycerin", stock=18,
        price=2900.0, category="Cleanser",
        description="Gentle micellar cleansing water for sensitive skin. Soothing and calming formula that cleanses without irritation.",
        image_url=None),
    ProductCatalog(sku="AVE-SEN-025", name="Avene Skin Recovery Cream",
        ingredients_csv="Avene Thermal Spring Water,Glycerin,Ceramides,Panthenol,Chamomile", stock=13,
        price=3600.0, category="Moisturizer",
        description="Recovery cream for sensitive and reactive skin. Gentle soothing formula that calms and repairs stressed skin.",
        image_url=None),
    ProductCatalog(sku="RND-SEN-026", name="Round Lab Birch Juice Moisturizing Toner",
        ingredients_csv="Birch Juice,Panthenol,Centella,Aloe Vera,Glycerin", stock=17,
        price=2100.0, category="Toner",
        description="Hydrating toner with birch juice and panthenol for sensitive skin. Gentle soothing formula for calm skin.",
        image_url=None),
    ProductCatalog(sku="CEL-SEN-027", name="Cetaphil Gentle Skin Cleanser",
        ingredients_csv="Glycerin,Panthenol,Niacinamide,Aloe Vera", stock=32,
        price=1600.0, category="Cleanser",
        description="Dermatologist-recommended gentle cleanser for sensitive skin. Soothing and calming formula for all skin types.",
        image_url=None),
    ProductCatalog(sku="MIS-SEN-028", name="Missha Time Revolution Artemisia Treatment Essence",
        ingredients_csv="Artemisia,Centella,Aloe Vera,Panthenol,Glycerin", stock=15,
        price=2400.0, category="Essence",
        description="Calming essence with artemisia and centella for sensitive skin. Reduces redness and soothes irritated skin.",
        image_url=None),
    ProductCatalog(sku="DRR-SEN-029", name="Dr Rashel Aloe Vera Soothing Gel",
        ingredients_csv="Aloe Vera,Centella,Panthenol,Chamomile,Glycerin", stock=28,
        price=800.0, category="Gel",
        description="Pure aloe vera soothing gel for sensitive and irritated skin. Calming formula that reduces redness and inflammation.",
        image_url=None),
    ProductCatalog(sku="SKN-SEN-030", name="Skintific Aloe Vera Calming Moisturizer",
        ingredients_csv="Aloe Vera,Panthenol,Centella,Ceramides,Glycerin", stock=19,
        price=1200.0, category="Moisturizer",
        description="Aloe vera calming moisturizer for sensitive skin. Gentle soothing formula that reduces redness and maintains calm skin.",
        image_url=None),

    # ── ACNE / BLEMISH ─────────────────────────────────────────────────────
    ProductCatalog(sku="DRR-ACN-031", name="Dr Rashel Tea Tree Blemish Control Spot Treatment",
        ingredients_csv="Tea Tree,Salicylic Acid,Niacinamide,Zinc,Benzoyl Peroxide", stock=27,
        price=700.0, category="Treatment",
        description="Targeted acne spot treatment with tea tree oil and salicylic acid. Clears pimples and blemishes fast.",
        image_url=None),
    ProductCatalog(sku="NEU-ACN-032", name="Neutrogena Rapid Clear Acne Face Wash",
        ingredients_csv="Salicylic Acid,Glycerin,Tea Tree,Niacinamide", stock=23,
        price=900.0, category="Cleanser",
        description="Salicylic acid acne face wash that clears blemishes and prevents new pimples. Oil control for acne-prone skin.",
        image_url=None),
    ProductCatalog(sku="LAR-ACN-033", name="La Roche-Posay Effaclar Duo+ Acne Treatment",
        ingredients_csv="Benzoyl Peroxide,Niacinamide,Salicylic Acid,Zinc,Glycerin", stock=15,
        price=3800.0, category="Treatment",
        description="Dual-action acne treatment with benzoyl peroxide and niacinamide. Clears existing blemishes and prevents new breakouts.",
        image_url=None),
    ProductCatalog(sku="BSK-ACN-034", name="Benzac AC Benzoyl Peroxide 5% Gel",
        ingredients_csv="Benzoyl Peroxide,Glycerin,Aloe Vera", stock=20,
        price=1200.0, category="Treatment",
        description="Benzoyl peroxide acne gel that kills acne-causing bacteria. Effective blemish and pimple treatment.",
        image_url=None),
    ProductCatalog(sku="PON-ACN-035", name="Pond's Clear Solutions Acne Clear Face Wash",
        ingredients_csv="Salicylic Acid,Niacinamide,Tea Tree,Glycerin", stock=36,
        price=500.0, category="Cleanser",
        description="Acne-clearing face wash with salicylic acid and niacinamide. Clears blemishes and prevents pimple breakouts.",
        image_url=None),
    ProductCatalog(sku="CLN-ACN-036", name="Clean & Clear Advantage Acne Spot Treatment",
        ingredients_csv="Salicylic Acid,Tea Tree,Witch Hazel,Zinc", stock=24,
        price=850.0, category="Treatment",
        description="Fast-acting acne spot treatment with salicylic acid. Targets individual pimples and blemishes.",
        image_url=None),
    ProductCatalog(sku="SKN-ACN-037", name="Some By Mi Snail Truecica Miracle Repair Serum",
        ingredients_csv="Snail Mucin,Tea Tree,Centella,Niacinamide,Salicylic Acid", stock=17,
        price=2600.0, category="Serum",
        description="Miracle repair serum with snail mucin and tea tree for acne-prone skin. Heals blemishes and prevents future breakouts.",
        image_url=None),
    ProductCatalog(sku="DRR-ACN-038", name="Dr Rashel Salicylic Acid + Tea Tree Toner",
        ingredients_csv="Salicylic Acid,Tea Tree,Niacinamide,Witch Hazel,Zinc", stock=22,
        price=900.0, category="Toner",
        description="Clarifying toner with salicylic acid and tea tree for acne-prone skin. Unclogs pores and reduces blemishes.",
        image_url=None),
    ProductCatalog(sku="INN-ACN-039", name="Innisfree Bija Trouble Spot Essence",
        ingredients_csv="Torreya Seed,Tea Tree,Salicylic Acid,Niacinamide,Zinc", stock=18,
        price=1900.0, category="Essence",
        description="Trouble essence with bija oil and tea tree for acne-prone skin. Soothes blemishes and clears breakouts.",
        image_url=None),
    ProductCatalog(sku="ORD-ACN-040", name="The Ordinary Salicylic Acid 2% Solution",
        ingredients_csv="Salicylic Acid,Niacinamide,Witch Hazel,Zinc,Glycerin", stock=25,
        price=1500.0, category="Treatment",
        description="Salicylic acid exfoliating solution for acne-prone and blemish-prone skin. Unclogs pores and clears breakouts.",
        image_url=None),

    # ── HYPERPIGMENTATION / BRIGHTENING ────────────────────────────────────
    ProductCatalog(sku="DRR-VTC-041", name="Dr Rashel Vitamin C Brightening Serum",
        ingredients_csv="Vitamin C,Niacinamide,Alpha Arbutin,Glycerin,Hyaluronic Acid", stock=17,
        price=1400.0, category="Serum",
        description="Vitamin C brightening serum with alpha arbutin to fade dark spots and hyperpigmentation. Radiance boosting formula.",
        image_url=None),
    ProductCatalog(sku="ORD-ARB-042", name="The Ordinary Alpha Arbutin 2% + HA",
        ingredients_csv="Alpha Arbutin,Hyaluronic Acid,Vitamin C,Niacinamide", stock=20,
        price=1900.0, category="Serum",
        description="Alpha arbutin serum for reducing dark spots and uneven pigmentation. Brightening formula for even skin tone.",
        image_url=None),
    ProductCatalog(sku="GLU-WHT-043", name="Glutathione Whitening Brightening Cream",
        ingredients_csv="Glutathione,Vitamin C,Kojic Acid,Niacinamide,Alpha Arbutin", stock=13,
        price=1300.0, category="Moisturizer",
        description="Whitening brightening cream with kojic acid and vitamin C to even skin tone and reduce dark spots.",
        image_url=None),
    ProductCatalog(sku="OLE-BRT-044", name="Olay Natural White All in One Fairness Cream",
        ingredients_csv="Vitamin C,Niacinamide,Alpha Arbutin,Glycerin,Vitamin B3", stock=30,
        price=1100.0, category="Moisturizer",
        description="All-in-one fairness cream with vitamin C and niacinamide. Brightens dark spots and evens skin tone.",
        image_url=None),
    ProductCatalog(sku="SKN-BRT-045", name="Skintific Cover All Brightening Serum",
        ingredients_csv="Niacinamide,Alpha Arbutin,Vitamin C,Kojic Acid,Glycerin", stock=21,
        price=1500.0, category="Serum",
        description="Brightening serum with niacinamide and alpha arbutin. Fades dark spots and reduces hyperpigmentation.",
        image_url=None),
    ProductCatalog(sku="DRR-BRT-046", name="Dr Rashel Kojic Acid Dark Spot Corrector",
        ingredients_csv="Kojic Acid,Vitamin C,Alpha Arbutin,Niacinamide,Glycerin", stock=19,
        price=1200.0, category="Treatment",
        description="Dark spot corrector with kojic acid and vitamin C. Targets hyperpigmentation and brightens skin tone.",
        image_url=None),
    ProductCatalog(sku="MUL-BRT-047", name="Murad Rapid Dark Spot Correcting Serum",
        ingredients_csv="Vitamin C,Resorcinol,Glycolic Acid,Niacinamide,Alpha Arbutin", stock=10,
        price=6500.0, category="Serum",
        description="Clinically proven dark spot correcting serum with vitamin C. Visibly reduces dark spots and hyperpigmentation.",
        image_url=None),
    ProductCatalog(sku="ORD-VTC-048", name="The Ordinary Vitamin C Suspension 23% + HA",
        ingredients_csv="Vitamin C,Hyaluronic Acid,Niacinamide,Glycerin", stock=18,
        price=2100.0, category="Serum",
        description="High-concentration vitamin C serum for brightening and radiance. Fades dark spots and improves uneven tone.",
        image_url=None),
    ProductCatalog(sku="GRN-BRT-049", name="Garnier Bright Complete Vitamin C Serum",
        ingredients_csv="Vitamin C,Niacinamide,Alpha Arbutin,Glycerin", stock=26,
        price=950.0, category="Serum",
        description="Vitamin C brightening serum that visibly reduces dark spots and uneven tone. Radiance-boosting formula.",
        image_url=None),
    ProductCatalog(sku="ISN-BRT-050", name="Isntree Hyaluronic Acid Watery Sun Gel SPF 50+",
        ingredients_csv="Hyaluronic Acid,Niacinamide,Vitamin C,Zinc Oxide,Glycerin", stock=16,
        price=2400.0, category="Sunscreen",
        description="Watery sun gel with hyaluronic acid and niacinamide. Brightens skin while protecting against UV-triggered dark spots.",
        image_url=None),

    # ── COMBINATION / NORMAL ───────────────────────────────────────────────
    ProductCatalog(sku="DRR-BAL-051", name="Dr Rashel Balance Niacinamide + Vitamin C Cream",
        ingredients_csv="Niacinamide,Vitamin C,Hyaluronic Acid,Glycerin", stock=22,
        price=1100.0, category="Moisturizer",
        description="Balancing moisturizer with niacinamide and vitamin C for combination skin. Maintains radiance and hydration.",
        image_url=None),
    ProductCatalog(sku="ORD-NIA-052", name="The Ordinary Niacinamide 10% + Zinc 1%",
        ingredients_csv="Niacinamide,Zinc,Glycerin,Vitamin C", stock=28,
        price=1700.0, category="Serum",
        description="High-strength niacinamide serum with zinc for pore minimizing and skin balance. Glow-enhancing formula.",
        image_url=None),
    ProductCatalog(sku="SKN-BAL-053", name="Skintific Mugwort + Niacinamide Balance Toner",
        ingredients_csv="Niacinamide,Mugwort,Hyaluronic Acid,Glycerin,Vitamin C", stock=20,
        price=1400.0, category="Toner",
        description="Balancing toner with niacinamide and mugwort for combination skin. Hydrates and maintains natural glow.",
        image_url=None),
    ProductCatalog(sku="NTG-BAL-054", name="Neutrogena Hydro Boost Gel Cream",
        ingredients_csv="Hyaluronic Acid,Glycerin,Ceramides,Niacinamide,Vitamin C", stock=21,
        price=2600.0, category="Moisturizer",
        description="Gel cream with hyaluronic acid for normal and combination skin. Lightweight hydration that maintains radiance.",
        image_url=None),
    ProductCatalog(sku="CEL-BAL-055", name="Cetaphil Daily Facial Moisturizer SPF 50",
        ingredients_csv="Niacinamide,Glycerin,Vitamin C,Zinc Oxide,Hyaluronic Acid", stock=18,
        price=2200.0, category="Moisturizer",
        description="Daily moisturizer with SPF 50 for normal to combination skin. Maintains moisture balance and vitamin C glow.",
        image_url=None),
    ProductCatalog(sku="INN-BAL-056", name="Innisfree Green Tea Seed Serum",
        ingredients_csv="Green Tea,Hyaluronic Acid,Glycerin,Niacinamide,Vitamin C", stock=15,
        price=3200.0, category="Serum",
        description="Green tea serum for balanced and hydrated skin. Antioxidant-rich formula that maintains radiance and vitality.",
        image_url=None),
    ProductCatalog(sku="GRN-BAL-057", name="Garnier Micellar Cleansing Water All Skin Types",
        ingredients_csv="Glycerin,Niacinamide,Aloe Vera,Panthenol", stock=38,
        price=700.0, category="Cleanser",
        description="Micellar water for all skin types including combination. Gentle cleansing formula that maintains skin balance.",
        image_url=None),
    ProductCatalog(sku="PON-BAL-058", name="Pond's Bright Beauty Serum Cream",
        ingredients_csv="Niacinamide,Vitamin C,Glycerin,Hyaluronic Acid,Alpha Arbutin", stock=30,
        price=850.0, category="Moisturizer",
        description="Brightening serum cream for normal and combination skin. Vitamin C formula that maintains radiance.",
        image_url=None),
    ProductCatalog(sku="KIE-BAL-059", name="Kiehl's Ultra Facial Cream",
        ingredients_csv="Glycerin,Hyaluronic Acid,Squalane,Niacinamide,Vitamin E", stock=12,
        price=5500.0, category="Moisturizer",
        description="Iconic moisturizer for normal to combination skin. Balances hydration and maintains skin glow all day.",
        image_url=None),
    ProductCatalog(sku="SKN-BAL-060", name="Skintific Moisture Surge Hydrating Serum",
        ingredients_csv="Hyaluronic Acid,Niacinamide,Glycerin,Ceramides,Vitamin C", stock=23,
        price=1600.0, category="Serum",
        description="Hydrating serum for combination skin. Balances moisture levels and maintains a healthy natural glow.",
        image_url=None),

    # ── ANTI-AGING ────────────────────────────────────────────────────────
    ProductCatalog(sku="ORD-RET-061", name="The Ordinary Retinol 0.5% in Squalane",
        ingredients_csv="Retinol,Squalane,Vitamin E,Peptides,Hyaluronic Acid", stock=12,
        price=2400.0, category="Serum",
        description="Retinol anti-aging serum in squalane for wrinkle reduction and skin firmness. Peptide-boosted formula.",
        image_url=None),
    ProductCatalog(sku="OLA-PEP-062", name="Olay Regenerist Micro-Sculpting Peptide Cream",
        ingredients_csv="Peptides,Niacinamide,Hyaluronic Acid,Vitamin C,Glycerin", stock=16,
        price=3500.0, category="Moisturizer",
        description="Anti-aging moisturizer with peptides for skin firming and wrinkle reduction. Collagen-boosting formula.",
        image_url=None),
    ProductCatalog(sku="RET-ANT-063", name="RoC Retinol Correxion Anti-Wrinkle Serum",
        ingredients_csv="Retinol,Collagen,Peptides,Hyaluronic Acid,Vitamin C", stock=10,
        price=4500.0, category="Serum",
        description="Anti-wrinkle retinol serum that visibly reduces fine lines and firms skin. Collagen-boosting peptide formula.",
        image_url=None),
    ProductCatalog(sku="NTG-RET-064", name="Neutrogena Rapid Wrinkle Repair Retinol Cream",
        ingredients_csv="Retinol,Hyaluronic Acid,Glycerin,Peptides,Vitamin E", stock=14,
        price=3800.0, category="Moisturizer",
        description="Rapid action retinol cream for wrinkle reduction and skin firming. Anti-aging formula for mature skin.",
        image_url=None),
    ProductCatalog(sku="OLA-ANT-065", name="Olay Total Effects 7-in-1 Anti-Aging Cream",
        ingredients_csv="Niacinamide,Vitamin C,Retinol,Peptides,Glycerin,Hyaluronic Acid", stock=18,
        price=2900.0, category="Moisturizer",
        description="7-in-1 anti-aging moisturizer that fights wrinkles, fine lines, and uneven skin tone simultaneously.",
        image_url=None),
    ProductCatalog(sku="ORD-PEP-066", name="The Ordinary Buffet Multi-Technology Peptide Serum",
        ingredients_csv="Peptides,Hyaluronic Acid,Niacinamide,Glycerin,Vitamin C", stock=17,
        price=3200.0, category="Serum",
        description="Multi-peptide serum targeting multiple signs of aging. Firms skin, reduces wrinkles and fine lines.",
        image_url=None),
    ProductCatalog(sku="EST-ANT-067", name="Estee Lauder Advanced Night Repair Serum",
        ingredients_csv="Hyaluronic Acid,Retinol,Peptides,Ceramides,Niacinamide", stock=9,
        price=8500.0, category="Serum",
        description="Iconic anti-aging night repair serum with hyaluronic acid and retinol. Repairs skin overnight, reduces wrinkles.",
        image_url=None),
    ProductCatalog(sku="LAR-RET-068", name="La Roche-Posay Retinol B3 Anti-Aging Serum",
        ingredients_csv="Retinol,Niacinamide,Vitamin B3,Glycerin,Ceramides", stock=11,
        price=5200.0, category="Serum",
        description="Retinol anti-aging serum with niacinamide for wrinkle reduction and skin firming. Gentle formula.",
        image_url=None),
    ProductCatalog(sku="SKN-ANT-069", name="Skintific Collagen Booster Anti-Aging Serum",
        ingredients_csv="Collagen,Peptides,Retinol,Hyaluronic Acid,Vitamin C", stock=19,
        price=1900.0, category="Serum",
        description="Collagen-boosting serum with peptides for anti-aging benefits. Reduces wrinkles and firms skin.",
        image_url=None),
    ProductCatalog(sku="DRR-RET-070", name="Dr Rashel Retinol Anti-Aging Face Cream",
        ingredients_csv="Retinol,Peptides,Vitamin C,Hyaluronic Acid,Glycerin", stock=20,
        price=1600.0, category="Moisturizer",
        description="Retinol anti-aging cream for wrinkle reduction and skin firming. Peptide-enriched formula for mature skin.",
        image_url=None),

    # ── SPF / SUNSCREEN ───────────────────────────────────────────────────
    ProductCatalog(sku="NEU-SPF-071", name="Neutrogena Ultra Sheer Sunscreen SPF 50",
        ingredients_csv="Zinc Oxide,Titanium Dioxide,Vitamin E,Glycerin", stock=26,
        price=1600.0, category="Sunscreen",
        description="Lightweight daily sunscreen SPF 50 for all skin types. Oil-free formula that protects against UV damage.",
        image_url=None),
    ProductCatalog(sku="LAR-SPF-072", name="La Roche-Posay Anthelios UVmune SPF 50+",
        ingredients_csv="Mexoryl 400,Titanium Dioxide,Niacinamide,Glycerin,Vitamin E", stock=14,
        price=4800.0, category="Sunscreen",
        description="Advanced broad-spectrum sunscreen SPF 50+ with mexoryl technology. Protects against UVA and UVB rays.",
        image_url=None),
    ProductCatalog(sku="CEL-SPF-073", name="Cetaphil Sun SPF 50+ Light Gel",
        ingredients_csv="Zinc Oxide,Titanium Dioxide,Glycerin,Niacinamide", stock=20,
        price=2800.0, category="Sunscreen",
        description="Lightweight sun gel SPF 50+ for sensitive and all skin types. Gentle daily sunscreen protection.",
        image_url=None),
    ProductCatalog(sku="GRN-SPF-074", name="Garnier Ambre Solaire Super UV SPF 50+",
        ingredients_csv="Titanium Dioxide,Niacinamide,Vitamin C,Glycerin,Zinc Oxide", stock=22,
        price=1400.0, category="Sunscreen",
        description="Super UV protection SPF 50+ with vitamin C for daily use. Brightening sun protection for all skin types.",
        image_url=None),
    ProductCatalog(sku="SKN-SPF-075", name="Skintific Sunscreen SPF 50+ PA++++",
        ingredients_csv="Zinc Oxide,Niacinamide,Hyaluronic Acid,Vitamin C,Glycerin", stock=24,
        price=1300.0, category="Sunscreen",
        description="High protection sunscreen SPF 50+ PA++++ with niacinamide and vitamin C. Lightweight daily UV protection.",
        image_url=None),
    ProductCatalog(sku="DRR-SPF-076", name="Dr Rashel Sunblock Cream SPF 50",
        ingredients_csv="Zinc Oxide,Titanium Dioxide,Niacinamide,Aloe Vera,Glycerin", stock=28,
        price=900.0, category="Sunscreen",
        description="Affordable sunblock cream SPF 50 with niacinamide and aloe vera. Daily UV protection for all skin types.",
        image_url=None),
    ProductCatalog(sku="ISN-SPF-077", name="Isntree Hyaluronic Acid Sun Cream SPF 50+",
        ingredients_csv="Hyaluronic Acid,Niacinamide,Zinc Oxide,Glycerin,Ceramides", stock=16,
        price=2600.0, category="Sunscreen",
        description="Hydrating sun cream SPF 50+ with hyaluronic acid. Moisturizing UV protection for dry and sensitive skin.",
        image_url=None),

    # ── EXFOLIANTS / MASKS ────────────────────────────────────────────────
    ProductCatalog(sku="ORD-AHA-081", name="The Ordinary AHA 30% + BHA 2% Peeling Solution",
        ingredients_csv="Glycolic Acid,Salicylic Acid,Lactic Acid,Niacinamide,Hyaluronic Acid", stock=15,
        price=2800.0, category="Exfoliant",
        description="Professional-strength AHA BHA peeling solution for clear and bright skin. Removes dead skin cells and unclogs pores.",
        image_url=None),
    ProductCatalog(sku="SKN-MSK-082", name="Skintific Mugwort Clay Mask",
        ingredients_csv="Clay,Mugwort,Niacinamide,Salicylic Acid,Charcoal", stock=19,
        price=1400.0, category="Mask",
        description="Detoxifying clay mask with mugwort and charcoal for deep cleansing. Removes impurities and controls oil.",
        image_url=None),
    ProductCatalog(sku="DRR-MSK-083", name="Dr Rashel Black Mask Blackhead Remover",
        ingredients_csv="Charcoal,Clay,Salicylic Acid,Tea Tree,Niacinamide", stock=22,
        price=700.0, category="Mask",
        description="Charcoal peel-off mask that removes blackheads and unclogs pores. Deep cleansing formula for clear skin.",
        image_url=None),
    ProductCatalog(sku="INN-MSK-084", name="Innisfree Super Volcanic Pore Clay Mask",
        ingredients_csv="Volcanic Ash,Clay,Salicylic Acid,Niacinamide,Zinc", stock=14,
        price=2200.0, category="Mask",
        description="Volcanic clay mask for deep pore cleansing. Absorbs excess oil and refines pores for clear skin.",
        image_url=None),
    ProductCatalog(sku="GRN-EXF-085", name="Garnier Skin Naturals Light Complete Scrub",
        ingredients_csv="Glycolic Acid,Niacinamide,Vitamin C,Alpha Arbutin,Glycerin", stock=24,
        price=650.0, category="Exfoliant",
        description="Brightening face scrub with glycolic acid and vitamin C. Exfoliates dead skin and reveals brighter tone.",
        image_url=None),
    ProductCatalog(sku="LAR-EXF-086", name="La Roche-Posay Effaclar Micro Peeling Gel",
        ingredients_csv="Salicylic Acid,Glycolic Acid,Niacinamide,Zinc,Glycerin", stock=12,
        price=3600.0, category="Exfoliant",
        description="Micro-peeling gel with salicylic and glycolic acid. Unclogs pores and smooths skin texture effectively.",
        image_url=None),
    ProductCatalog(sku="SKN-MSK-087", name="Skintific Mugwort Pore Reducing Sheet Mask",
        ingredients_csv="Mugwort,Centella,Niacinamide,Aloe Vera,Glycerin", stock=30,
        price=350.0, category="Mask",
        description="Soothing sheet mask with mugwort and centella. Reduces pores and calms skin for a clear complexion.",
        image_url=None),
    ProductCatalog(sku="GRN-MSK-088", name="Garnier Moisture Bomb Sheet Mask",
        ingredients_csv="Hyaluronic Acid,Glycerin,Aloe Vera,Niacinamide,Vitamin C", stock=35,
        price=300.0, category="Mask",
        description="Moisture bomb sheet mask with hyaluronic acid for deep hydration. Plumps and revitalises dry skin.",
        image_url=None),

    # ── EYE CARE ─────────────────────────────────────────────────────────
    ProductCatalog(sku="CEL-EYE-091", name="CeraVe Eye Repair Cream",
        ingredients_csv="Ceramides,Hyaluronic Acid,Niacinamide,Peptides,Glycerin", stock=16,
        price=2600.0, category="Eye Cream",
        description="Eye repair cream with ceramides and peptides for dark circles and fine lines around the eye area.",
        image_url=None),
    ProductCatalog(sku="OLA-EYE-092", name="Olay Eyes Ultimate Eye Cream",
        ingredients_csv="Peptides,Niacinamide,Hyaluronic Acid,Vitamin C,Retinol", stock=12,
        price=3800.0, category="Eye Cream",
        description="Ultimate eye cream with peptides for puffiness, dark circles and wrinkles. Anti-aging formula for eye area.",
        image_url=None),
    ProductCatalog(sku="DRR-EYE-093", name="Dr Rashel Vitamin C Eye Serum",
        ingredients_csv="Vitamin C,Peptides,Hyaluronic Acid,Niacinamide,Caffeine", stock=18,
        price=1100.0, category="Eye Serum",
        description="Brightening eye serum with vitamin C and caffeine. Reduces dark circles and brightens the eye area.",
        image_url=None),
    ProductCatalog(sku="SKN-EYE-094", name="Skintific Vitamin C Brightening Eye Cream",
        ingredients_csv="Vitamin C,Niacinamide,Peptides,Hyaluronic Acid,Glycerin", stock=17,
        price=1400.0, category="Eye Cream",
        description="Brightening eye cream with vitamin C and peptides. Reduces dark circles and fine lines around eyes.",
        image_url=None),

    # ── TONERS & ESSENCES ─────────────────────────────────────────────────
    ProductCatalog(sku="MIS-TON-096", name="Missha Time Revolution First Treatment Essence",
        ingredients_csv="Fermented Yeast,Niacinamide,Hyaluronic Acid,Glycerin,Panthenol", stock=13,
        price=3500.0, category="Essence",
        description="Iconic fermented essence for skin glow and radiance. Balances skin and prepares for better serum absorption.",
        image_url=None),
    ProductCatalog(sku="INN-TON-097", name="Innisfree Jeju Volcanic Pore Toning Pad",
        ingredients_csv="Volcanic Ash,Niacinamide,Salicylic Acid,Hyaluronic Acid,Glycerin", stock=17,
        price=2100.0, category="Toner",
        description="Pore-toning pads with volcanic ash and niacinamide. Exfoliates and refines pores for smooth skin.",
        image_url=None),
    ProductCatalog(sku="RND-TON-098", name="Round Lab 1025 Dokdo Toner",
        ingredients_csv="Sea Water Mineral,Hyaluronic Acid,Glycerin,Niacinamide,Ceramides", stock=16,
        price=2000.0, category="Toner",
        description="Mineral-rich hydrating toner with hyaluronic acid. Balances pH and deeply hydrates for healthy skin.",
        image_url=None),
    ProductCatalog(sku="ORD-TON-099", name="The Ordinary Glycolic Acid 7% Toning Solution",
        ingredients_csv="Glycolic Acid,Niacinamide,Aloe Vera,Hyaluronic Acid,Glycerin", stock=21,
        price=1800.0, category="Toner",
        description="Exfoliating glycolic acid toner for improved skin texture and radiance. Removes dead skin cells gently.",
        image_url=None),
    ProductCatalog(sku="DRR-TON-100", name="Dr Rashel Vitamin C Brightening Toner",
        ingredients_csv="Vitamin C,Niacinamide,Alpha Arbutin,Glycerin,Hyaluronic Acid", stock=22,
        price=850.0, category="Toner",
        description="Brightening vitamin C toner that evens skin tone and reduces dark spots. Radiance-boosting daily toner.",
        image_url=None),

    # ── DEHYDRATION ───────────────────────────────────────────────────────
    ProductCatalog(sku="SKN-DEH-101", name="Skintific 10% Niacinamide Hydrating Serum",
        ingredients_csv="Niacinamide,Hyaluronic Acid,Glycerin,Ceramides,Squalane", stock=22,
        price=1500.0, category="Serum",
        description="High-dose niacinamide hydrating serum for dehydrated skin. Deeply moisturizing formula that plumps skin.",
        image_url=None),
    ProductCatalog(sku="NTG-DEH-102", name="Neutrogena Hydro Boost Hydrating Serum",
        ingredients_csv="Hyaluronic Acid,Glycerin,Ceramides,Squalane,Vitamin E", stock=19,
        price=2900.0, category="Serum",
        description="Intensely hydrating serum with hyaluronic acid for dehydrated skin. Water-burst technology for all-day moisture.",
        image_url=None),
    ProductCatalog(sku="DRR-DEH-103", name="Dr Rashel Hyaluronic Acid Water Plumping Serum",
        ingredients_csv="Hyaluronic Acid,Glycerin,Ceramides,Water,Squalane", stock=24,
        price=1300.0, category="Serum",
        description="Water plumping serum with multiple hyaluronic acid weights. Deeply hydrates dehydrated skin for a plumped look.",
        image_url=None),
    ProductCatalog(sku="CEL-DEH-104", name="CeraVe Skin Renewing Vitamin C Serum",
        ingredients_csv="Vitamin C,Ceramides,Hyaluronic Acid,Niacinamide,Glycerin", stock=17,
        price=3200.0, category="Serum",
        description="Vitamin C serum with ceramides for hydrating and brightening dehydrated skin. Restores moisture and radiance.",
        image_url=None),

    # ── BODY CARE ────────────────────────────────────────────────────────
    ProductCatalog(sku="DRR-BOD-111", name="Dr Rashel Kojic Acid Body Lotion",
        ingredients_csv="Kojic Acid,Vitamin C,Alpha Arbutin,Niacinamide,Glycerin", stock=20,
        price=1200.0, category="Body Lotion",
        description="Kojic acid brightening body lotion for even skin tone. Reduces dark spots and hyperpigmentation on body.",
        image_url=None),
    ProductCatalog(sku="EST-BOD-112", name="Estelin Glutathione Brightening Body Lotion",
        ingredients_csv="Glutathione,Vitamin C,Kojic Acid,Niacinamide,Shea Butter", stock=18,
        price=1400.0, category="Body Lotion",
        description="Glutathione brightening body lotion for radiant and even skin tone. Anti-dark spot formula for smooth skin.",
        image_url=None),
    ProductCatalog(sku="VAZ-BOD-113", name="Vaseline Healthy White Complete 10 Lightening Lotion",
        ingredients_csv="Glycerin,Vitamin B3,Petroleum Jelly,Shea Butter,Vitamin E", stock=35,
        price=750.0, category="Body Lotion",
        description="Complete 10 body lotion for healthy glowing skin. Nourishing formula that moisturizes and brightens skin.",
        image_url=None),
    ProductCatalog(sku="AVN-BOD-114", name="Aveeno Skin Relief Moisturizing Lotion",
        ingredients_csv="Oat,Glycerin,Shea Butter,Ceramides,Panthenol", stock=22,
        price=2200.0, category="Body Lotion",
        description="Skin relief lotion with oat for very dry and sensitive skin. Soothing formula for itchy and irritated skin.",
        image_url=None),
    ProductCatalog(sku="BIO-BOD-115", name="Bioderma ABCDerm Smoothing Body Milk",
        ingredients_csv="Shea Butter,Glycerin,Ceramides,Panthenol,Aloe Vera", stock=14,
        price=3200.0, category="Body Milk",
        description="Smoothing body milk for dry skin. Nourishing and soothing formula with ceramides and shea butter.",
        image_url=None),

    # ── LIP CARE ─────────────────────────────────────────────────────────
    ProductCatalog(sku="DRR-LIP-121", name="Dr Rashel Vitamin C Lip Serum",
        ingredients_csv="Vitamin C,Hyaluronic Acid,Glycerin,Collagen,Peptides", stock=26,
        price=600.0, category="Lip Care",
        description="Brightening lip serum with vitamin C and hyaluronic acid. Plumps and moisturizes lips for a healthy look.",
        image_url=None),
    ProductCatalog(sku="SKN-LIP-122", name="Skintific Moisturizing Lip Sleeping Mask",
        ingredients_csv="Hyaluronic Acid,Shea Butter,Vitamin E,Glycerin,Ceramides", stock=20,
        price=900.0, category="Lip Care",
        description="Overnight lip sleeping mask with hyaluronic acid and shea butter. Deeply moisturizes and repairs dry lips.",
        image_url=None),
]


def seed_products(db: Session) -> None:
    """Seed the product catalog with default products if the table is empty.

    Descriptions are intentionally cleared to None so that:
      - WooCommerce sync (drrashel.co.ke) provides the authoritative description
      - Admins can write descriptions from the Admin Products page
      - No generic placeholder text appears on the storefront
    """
    existing = db.execute(select(ProductCatalog.sku)).first()
    if existing:
        return

    # Strip hardcoded descriptions before inserting — they are kept in the
    # DEFAULT_PRODUCTS list only as dev-time references, not production copy.
    for product in DEFAULT_PRODUCTS:
        product.description = None

    db.add_all(DEFAULT_PRODUCTS)
    db.commit()
