from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.product import ProductCatalog

DEFAULT_PRODUCTS = [
    # OILY SKIN PRODUCTS
    ProductCatalog(
        sku="DRR-ACN-001",
        name="Dr Rashel Salicylic Acid Clear Skin Serum",
        ingredients_csv="Salicylic Acid,Niacinamide,Tea Tree,Zinc,Glycerin,Aloe Vera",
        stock=24,
        price=1200.0,
        description="Oil control serum with salicylic acid and niacinamide to clear pores and reduce acne blemishes. Mattifying formula for oily skin.",
        category="Serum",
        image_url=None,
    ),
    ProductCatalog(
        sku="DRR-OIL-002",
        name="Dr Rashel Niacinamide Pore Minimizer Toner",
        ingredients_csv="Niacinamide,Zinc,Salicylic Acid,Witch Hazel,Glycerin",
        stock=20,
        price=950.0,
        description="Niacinamide toner for pore minimizing and oil control. Mattifying formula that balances sebum production.",
        category="Toner",
        image_url=None,
    ),
    ProductCatalog(
        sku="NEU-CLY-003",
        name="Neutrogena Deep Clean Clay Face Wash",
        ingredients_csv="Clay,Charcoal,Salicylic Acid,Glycerin",
        stock=30,
        price=800.0,
        description="Deep clean charcoal clay face wash that draws out impurities from pores. Ideal for oily and combination skin.",
        category="Cleanser",
        image_url=None,
    ),
    ProductCatalog(
        sku="GRN-OIL-004",
        name="Garnier Oil Control Moisturizer SPF 15",
        ingredients_csv="Niacinamide,Zinc,Glycerin,Vitamin E",
        stock=25,
        price=750.0,
        description="Lightweight oil control moisturizer with SPF protection. Mattifying formula for oily to combination skin.",
        category="Moisturizer",
        image_url=None,
    ),
    # DRY SKIN PRODUCTS
    ProductCatalog(
        sku="EST-HYD-010",
        name="Estelin Deep Hydration Hyaluronic Acid Cream",
        ingredients_csv="Hyaluronic Acid,Ceramides,Glycerin,Shea Butter,Squalane",
        stock=18,
        price=1500.0,
        description="Deeply hydrating moisturizer with hyaluronic acid and ceramides for dry and dehydrated skin. Nourishing formula that restores moisture barrier.",
        category="Moisturizer",
        image_url=None,
    ),
    ProductCatalog(
        sku="CET-HYD-011",
        name="CeraVe Hydrating Facial Cleanser",
        ingredients_csv="Ceramides,Hyaluronic Acid,Glycerin,Niacinamide",
        stock=22,
        price=1800.0,
        description="Gentle hydrating cleanser with ceramides and hyaluronic acid. Nourishing formula that cleanses without stripping dry skin.",
        category="Cleanser",
        image_url=None,
    ),
    ProductCatalog(
        sku="EST-SHE-012",
        name="Estelin Shea Butter Intensive Body Lotion",
        ingredients_csv="Shea Butter,Glycerin,Vitamin E,Squalane,Ceramides",
        stock=15,
        price=1100.0,
        description="Intensively nourishing body lotion with shea butter and vitamin E. Moisturizing formula for extremely dry skin.",
        category="Body Lotion",
        image_url=None,
    ),
    ProductCatalog(
        sku="ORD-HYA-013",
        name="The Ordinary Hyaluronic Acid 2% + B5",
        ingredients_csv="Hyaluronic Acid,Vitamin B5,Glycerin,Ceramides",
        stock=19,
        price=2200.0,
        description="Hydrating serum with multi-weight hyaluronic acid and vitamin B5. Plumps and hydrates dehydrated skin for a moisturized complexion.",
        category="Serum",
        image_url=None,
    ),
    # SENSITIVE SKIN PRODUCTS
    ProductCatalog(
        sku="AVN-SEN-020",
        name="Aveeno Calm + Restore Oat Gel Moisturizer",
        ingredients_csv="Oat,Panthenol,Aloe Vera,Ceramides,Glycerin",
        stock=14,
        price=2500.0,
        description="Gentle soothing gel moisturizer with oat and panthenol. Calming formula for sensitive skin that reduces redness and irritation.",
        category="Moisturizer",
        image_url=None,
    ),
    ProductCatalog(
        sku="LAR-SEN-021",
        name="La Roche-Posay Toleriane Gentle Cleanser",
        ingredients_csv="Ceramides,Glycerin,Niacinamide,Panthenol",
        stock=16,
        price=3200.0,
        description="Ultra-gentle soothing cleanser for sensitive skin. Calming formula with ceramides that maintains the skin barrier.",
        category="Cleanser",
        image_url=None,
    ),
    ProductCatalog(
        sku="CEN-SEN-022",
        name="Centella Asiatica Calming Serum",
        ingredients_csv="Centella,Aloe Vera,Chamomile,Panthenol,Glycerin",
        stock=21,
        price=1600.0,
        description="Centella asiatica calming serum for sensitive and irritated skin. Soothing formula with aloe and chamomile to reduce redness.",
        category="Serum",
        image_url=None,
    ),
    # ACNE / BLEMISH PRODUCTS
    ProductCatalog(
        sku="DRR-ACN-030",
        name="Dr Rashel Tea Tree Blemish Control Spot Treatment",
        ingredients_csv="Tea Tree,Salicylic Acid,Niacinamide,Zinc,Benzoyl Peroxide",
        stock=27,
        price=700.0,
        description="Targeted acne spot treatment with tea tree oil and salicylic acid. Clears pimples and blemishes fast with antibacterial action.",
        category="Treatment",
        image_url=None,
    ),
    ProductCatalog(
        sku="NEU-ACN-031",
        name="Neutrogena Rapid Clear Acne Face Wash",
        ingredients_csv="Salicylic Acid,Glycerin,Tea Tree,Niacinamide",
        stock=23,
        price=900.0,
        description="Salicylic acid acne face wash that clears blemishes and prevents new pimples. Oil control formula for acne-prone skin.",
        category="Cleanser",
        image_url=None,
    ),
    # HYPERPIGMENTATION / BRIGHTENING PRODUCTS
    ProductCatalog(
        sku="DRR-VTC-040",
        name="Dr Rashel Vitamin C Brightening Serum",
        ingredients_csv="Vitamin C,Niacinamide,Alpha Arbutin,Glycerin,Hyaluronic Acid",
        stock=17,
        price=1400.0,
        description="Vitamin C brightening serum with alpha arbutin to fade dark spots and hyperpigmentation. Radiance boosting formula for even skin tone.",
        category="Serum",
        image_url=None,
    ),
    ProductCatalog(
        sku="ORD-ARB-041",
        name="The Ordinary Alpha Arbutin 2% + HA",
        ingredients_csv="Alpha Arbutin,Hyaluronic Acid,Vitamin C,Niacinamide",
        stock=20,
        price=1900.0,
        description="Alpha arbutin serum for reducing dark spots, uneven pigmentation and brightening skin tone. Targets hyperpigmentation effectively.",
        category="Serum",
        image_url=None,
    ),
    ProductCatalog(
        sku="GLU-WHT-042",
        name="Glutathione Whitening Brightening Cream",
        ingredients_csv="Glutathione,Vitamin C,Kojic Acid,Niacinamide,Alpha Arbutin",
        stock=13,
        price=1300.0,
        description="Whitening brightening cream with kojic acid and vitamin C to even skin tone and reduce dark spots. For hyperpigmentation treatment.",
        category="Moisturizer",
        image_url=None,
    ),
    # COMBINATION / NORMAL SKIN PRODUCTS
    ProductCatalog(
        sku="DRR-BAL-050",
        name="Dr Rashel Balance Niacinamide + Vitamin C Cream",
        ingredients_csv="Niacinamide,Vitamin C,Hyaluronic Acid,Glycerin",
        stock=22,
        price=1100.0,
        description="Balancing moisturizer with niacinamide and vitamin C for combination skin. Maintains radiance and hydration.",
        category="Moisturizer",
        image_url=None,
    ),
    ProductCatalog(
        sku="ORD-NIA-051",
        name="The Ordinary Niacinamide 10% + Zinc 1%",
        ingredients_csv="Niacinamide,Zinc,Glycerin,Vitamin C",
        stock=28,
        price=1700.0,
        description="High-strength niacinamide serum with zinc for pore minimizing and skin balance. Glow-enhancing formula for normal to combination skin.",
        category="Serum",
        image_url=None,
    ),
    # ANTI-AGING PRODUCTS
    ProductCatalog(
        sku="ORD-RET-060",
        name="The Ordinary Retinol 0.5% in Squalane",
        ingredients_csv="Retinol,Squalane,Vitamin E,Peptides,Hyaluronic Acid",
        stock=12,
        price=2400.0,
        description="Retinol anti-aging serum in squalane for wrinkle reduction and skin firmness. Peptide-boosted formula for fine lines and aging skin.",
        category="Serum",
        image_url=None,
    ),
    ProductCatalog(
        sku="OLA-PEP-061",
        name="Olay Regenerist Micro-Sculpting Peptide Cream",
        ingredients_csv="Peptides,Niacinamide,Hyaluronic Acid,Vitamin C,Glycerin",
        stock=16,
        price=3500.0,
        description="Anti-aging moisturizer with peptides for skin firming and wrinkle reduction. Collagen-boosting formula for mature skin.",
        category="Moisturizer",
        image_url=None,
    ),
    # SPF / SUN PROTECTION
    ProductCatalog(
        sku="NEU-SPF-070",
        name="Neutrogena Ultra Sheer Sunscreen SPF 50",
        ingredients_csv="Zinc Oxide,Titanium Dioxide,Vitamin E,Glycerin",
        stock=26,
        price=1600.0,
        description="Lightweight daily sunscreen SPF 50 for all skin types. Oil-free formula that protects against UV damage.",
        category="Sunscreen",
        image_url=None,
    ),
]


def seed_products(db: Session) -> None:
    existing = db.execute(select(ProductCatalog.sku)).first()
    if existing:
        return
    db.add_all(DEFAULT_PRODUCTS)
    db.commit()
